import "./globals.css";
import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: "CMM SOFTWARE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
